#!/usr/bin/env php
<?php
declare(strict_types=1);

// SPDX-License-Identifier: GPL-3.0
/*
 *   OpenSubtitles Downloader
 *   Copyright (C) 2019 - 2021  Sacha Telgenhof
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

require 'vendor/autoload.php';

use Dotenv\Dotenv;
use Dotenv\Exception\InvalidPathException;
use fXmlRpc\Client as fXmlRpcClient;
use GuzzleHttp\Client as GuzzleClient;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\GuzzleException;
use League\CLImate\CLImate;
use Symfony\Component\Cache\Adapter\FilesystemAdapter;
use Symfony\Contracts\Cache\ItemInterface;

const APP_NAME = 'OpenSubtitles Downloader';
const APP_VERSION = '0.4';
$app_name = APP_NAME.' v'.APP_VERSION;
const SUBTITLES_PATH = __DIR__.DIRECTORY_SEPARATOR.'subtitles';
const API_URL = 'https://api.opensubtitles.org/xml-rpc';

$cli = new CLImate();

$cli->arguments->add([
    'imdb' => [
        'description' => 'IMDB Movie number',
    ],
    'help' => [
        'prefix' => 'h',
        'longPrefix' => 'help',
        'description' => 'Prints this usage description',
        'noValue' => true,
    ],
]);
$cli->arguments->parse();

if ($cli->arguments->defined('help')) {
    $cli->usage();
    exit();
}

$cli->description($app_name);
$cli->lightGreen($app_name);
$cli->lightGreen()->border('-*-', strlen($app_name));
$cli->clearLine();

$imdbID = $cli->arguments->get('imdb');
if (!$cli->arguments->exists('imdb') || empty($cli->arguments->get('imdb'))) {
    $input = $cli->input('Please enter an IMDB Movie Number:');
    $imdbID = $input->prompt();
}

try {
    $dotenv = Dotenv::createImmutable(__DIR__);
    $dotenv->load();
} catch (InvalidPathException $e) {
    $cli->error(sprintf('ERROR: %s', $e->getMessage()));
    exit();
}

$httpClient = new GuzzleClient();

try {
    $response = (new FilesystemAdapter())->get(md5($_ENV['OPEN_SUBTITLES_LANGUAGES'].$imdbID), function (ItemInterface $item) use ($imdbID): array {
        $item->expiresAfter(3600);

        $client = new fXmlRpcClient(API_URL);

        $response = $client->call('LogIn', [
            $_ENV['OPEN_SUBTITLES_USERNAME'],
            $_ENV['OPEN_SUBTITLES_PASSWORD'],
            'en',
            $_ENV['OPEN_SUBTITLES_USER_AGENT'],
        ]);

        if ('200 OK' === $response['status'] && !empty($response['token'])) {
            $response = $client->call(
                'SearchSubtitles',
                [$response['token'], [['sublanguageid' => $_ENV['OPEN_SUBTITLES_LANGUAGES'], 'imdbid' => $imdbID]]]
            );
        } else {
            throw new RuntimeException(sprintf('Unable to retrieve the subtitles (%s).', $response['status']));
        }

        return $response;
    });

    $subtitleCount = count($response['data']);

    if (0 === $subtitleCount) {
        $languages = implode(', ', array_map(static function ($a) {
            return locale_get_display_language($a, 'en');
        }, explode(',', $_ENV['OPEN_SUBTITLES_LANGUAGES'])));

        $cli->error(sprintf(
            'No %s subtitles found for IMDB ID %s. Please make sure to provide a valid IMDB ID.',
            $languages,
            (string) $imdbID
        ));
        exit();
    }

    $cli->br()->whisper(sprintf('%d %s found:', $subtitleCount, ($subtitleCount > 1 ? 'subtitles' : 'subtitle')));

    foreach ($response['data'] as $i => $hit) {
        $cli->whisper(sprintf(
            '%d: %s (%s) - %s - [%s] ',
            $i + 1,
            $hit['MovieName'],
            $hit['MovieYear'],
            $hit['IDSubtitleFile'],
            $hit['SubFileName']
        ));

        downloadSubtitle($hit, $httpClient);
    }
} catch (Exception | \Psr\Cache\InvalidArgumentException $e) {
    $cli->error(sprintf('ERROR: %s', $e->getMessage()));
}

$cli->br()->info('Completed.');

/**
 * Deflates a GZipped file.
 *
 * @param string $srcName the filepath of the original GZipped file
 * @param string $dstName the filepath of the uncompressed file (destination)
 */
function deflate(string $srcName, string $dstName): void
{
    $sfp = gzopen($srcName, 'rb');
    if (!$sfp) {
        throw new RuntimeException('unable to open source file for reading');
    }

    $fp = fopen($dstName, 'wb');
    if (!$fp) {
        throw new RuntimeException('unable to open destination file for writing');
    }

    while (!gzeof($sfp)) {
        $data = gzread($sfp, 4096);

        if (!$data) {
            throw new RuntimeException('unable to read source file');
        }

        fwrite($fp, $data, strlen($data));
    }

    gzclose($sfp);
    fclose($fp);
}

/**
 * Returns the directory path of the selected movie.
 *
 * It will create the directory if not exists.
 *
 * @param array<string> $hit search result (subtitle entry)
 */
function movieDirectory(array $hit): string
{
    $dir = SUBTITLES_PATH.DIRECTORY_SEPARATOR.$hit['MovieName'].' - '.$hit['MovieYear'];

    if (is_dir($dir)) {
        return $dir;
    }

    if (!mkdir($dir, 0777, true) && !is_dir($dir)) {
        throw new RuntimeException(sprintf('Directory "%s" was not created', $dir));
    }

    return $dir;
}

/**
 * Downloads the specified subtitle (if not yet downloaded).
 *
 * @param array<string> $hit subtitle entry
 */
function downloadSubtitle(array $hit, ClientInterface $client): void
{
    $movieDir = movieDirectory($hit);
    $subtitleFile = $movieDir.'/'.basename($hit['SubDownloadLink']);

    if (!is_readable($subtitleFile)) {
        try {
            $client->request(
                'GET',
                $hit['SubDownloadLink'],
                ['sink' => $subtitleFile]
            );
        } catch (Exception | GuzzleException $e) {
            throw new RuntimeException($e->getMessage());
        }
    }

    try {
        $srtFile = $movieDir.DIRECTORY_SEPARATOR.basename($subtitleFile, '.gz').'.srt';

        deflate($subtitleFile, $srtFile);
        transcode($srtFile, $hit['SubEncoding']);
    } catch (Throwable $e) {
        throw new RuntimeException($e->getMessage());
    }
}

/**
 * (Optionally) transcode the subtitle file.
 */
function transcode(string $srtFile, string $encoding): void
{
    if ($_ENV['OPEN_SUBTITLES_TARGET_ENCODING'] === $encoding) {
        return;
    }

    $srtContents = file_get_contents($srtFile);

    if (!$srtContents) {
        throw new RuntimeException('unable to open subtitle file for reading');
    }

    $srtContents = iconv($encoding, $_ENV['OPEN_SUBTITLES_TARGET_ENCODING'], $srtContents);

    if (!$srtContents) {
        throw new RuntimeException('unable to transcode the subtitle file');
    }

    file_put_contents($srtFile, $srtContents);
}
